### ISSUE TITLE
dirct issue with the target file results

### ISSUE THREAD

**Issue by ahmedshamel1** [yoshiinet/dcase2021_task2_ar_frame_seq_model#1]
Dear Prof. Yoshiharu 
  I am a bachelor student in Egypt.My name is Ahmed Nazmy . I am really intrested in your approach and I am trying to study it in my bachelor,but I have passed with some problems while training the model ,so I hope that you can help me to fix this error FileNotFoundError: [Errno 2] No such file or directory: "./model_fan_section_00_target_$tmp.pt" and I want to ask another question what should I change in the configuration file to use the domain independent model?
Thanks in advance

**Comment by yoshiinet** [comment]
Would you please send me a backtrace of the error so that I can analyze the cause of the error?

**Comment by ahmedshamel1** [comment]
(sess1) D:\deep3\dcase2021_task2_ar_frame_seq_model>python _00_train.py --mode dev
['fan']
generate dataset fan / train section_00 target: 3it [00:00, 95.04it/s]
Traceback (most recent call last):
  File "_00_train.py", line 198, in <module>
    main()
  File "_00_train.py", line 108, in main
    history_img_path = history_img_path,
  File "D:\deep3\dcase2021_task2_ar_frame_seq_model\model\pptunetf.py", line 980, in fit
    self.callback(model, epoch, history, save_best=True, save_freq=True)
  File "D:\deep3\dcase2021_task2_ar_frame_seq_model\model\pptunetf.py", line 992, in callback
    self.save_model(self.model_file_path, model, epochs=epoch+1)
  File "D:\deep3\dcase2021_task2_ar_frame_seq_model\model\pptunetf.py", line 654, in save_model
    return self._save(model, model_file_path, epochs)
  File "D:\deep3\dcase2021_task2_ar_frame_seq_model\model\pptunetf.py", line 629, in _save
    tmp_file)
  File "C:\Users\ahmed\Anaconda3\envs\sess1\lib\site-packages\torch\serialization.py", line 377, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "C:\Users\ahmed\Anaconda3\envs\sess1\lib\site-packages\torch\serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\ahmed\Anaconda3\envs\sess1\lib\site-packages\torch\serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: "../model/pptunetf/final/(512,1024,64,1,32,2.0)/(1,1,'pp-raw-tf6')/('linear',1024,256,'non-linear','pptunetf',6,8,'linear','none')/(0,0.0,0,32,-1,0.1,1e-05,1,0.1)/(5,'best')/(0,0.0,0,32,-1,0.1,1e-05,1,0.1)/(5,'best')/model_fan_section_00_target_$tmp.pt"

2)I also encountered a problem when using these params   model_for:                 
  f_machine : 0        
  f_section   : 0        
  f_target     : 0

the _00_train.py--mode dev was successful ,but when using  _00_train.py--mode eval (nothing happens) and I expected that the model should be trained with the additional dataset correct me if I am wrong please

3) What should I change in pptunetf-final.yaml to use the domain independent model ?

thank you so much for your help !!

**Comment by yoshiinet** [comment]
Thank you for sending the backtrace.

The following scripts in the top folder are not intended for direct use.
```
_00_train.py
_01_test.py
_03_collect_results.py
_04_run_job.py
```
These scripts are indirectly called from the scripts under the ".\run" folder (for example,  ".\run\pptunetf\pptunetf-final.py").
You could call the above scripts directly, but in that case you are responsible for giving full command line arguments by hands.
To reduce the pain, it is recommended to use the script under the run folder.

I apologize for any inconvenience caused by the lack of instructions on how to use it.

I have added the usage to "README.md", so please have a look.
If you continue to have problems, please feel free to contact me.

**Comment by ahmedshamel1** [comment]
I am very sorry for wasting your time and I really appreciate your help and guidance 
Thank you

**Comment by ahmedshamel1** [comment]
Prof. Yoshiharu 
- Can you please elaborate more how the data augmentation work and what do aug_count, aug_gadd aug_wcut stand for?
- does the transfer learning only works if the f_target =1 ?
-  can you relate the output in `summary_pptunetf_test.csv` file to the output in your technical paper at page 4
> Table 4: Harmonic means of AUC for test sections 00-02(in parentheses pAUC)

as the output differs in shape to the one in the paper
- when creating  a new env and running  the test command (pptunetf-test.py)without using the training command first (pptunetf-final.py) I still get the same results?

**Comment by yoshiinet** [comment]
(Q1) How does data augmentation work and what do **aug_count**, **aug_gadd** and **aug_wcut** stand for?
(A1) The data augmentation algorithm is as follows:
1.   Generate a list of data files.
2.   Repeat the list of files **aug_count** times.
3.   Read the waveform from the data files.
4.   Overlay a Gaussian random noise with a gain in the range 0 to **aug_gadd** on the waveform.
5.   Cut the **aug_wcut** samples before and after the waveform (change the position of the analysis frame).

For more information, see lines 113-128 of ["./data/task2_basedata.py"](https://github.com/yoshiinet/dcase2021_task2_ar_frame_seq_model/blob/main/data/task2_basedata.py#L113).

(Q2) Does transfer learning work only when **f_target** = 1?
(A2) Yes.
     For more information. See lines 668-682 in ["./model/pptunetf.py"](https://github.com/yoshiinet/dcase2021_task2_ar_frame_seq_model/blob/main/model/pptunetf.py#L668).

(Q3) What is the relationship between summary_pptunetf_test.csv and Table 4 of the technical paper?
(A3) Here's how to read the resulting .csv file (assuming it's open in MS Excel):
- Column _B_ contains how to handle machine types ("00 over all" ([the first 00 has no meaning]), "ToyCar", and so on).
- Column _C_ contains how to handle section ("arithmetic mean of all machine types, sections, and domains", "arithmetic mean", "harmonic mean", etc.),
- Column _D_ contains how to handle target ("a. m.[Arithmetic Mean] ToyCar", "h. m. [Harmonic Mean] ToyCar", "Source 00", etc.).
- Columns _E_ through _I_ contain the scores (AUC, pAUC, precision, etc.).
- Columns _AB_ through _BG_ contain experimental conditions.

For example, you can get the harmonic mean of ToyCar's AUC under the experimental conditions in row _11_ as the value in cell _E11_.

(Q4) Can I get the same result if I create a new env and run the test command (pptunetf-test.py) without using the training command (pptunetf-final.py) first?
(A4) Each command creates the results in separate folders, so they are independent of each other. Note that each command performs its own learning and evaluation.

**Comment by ahmedshamel1** [comment]
Prof. Yoshiharu
- I tried very hard to obtain the results in the technical paper for model B ,but I couldn't. I used the command (pptunetf-final.py) with version 4a ,shall something else be changed or shall I use the  (pptunetf-test.py) because I am confused?
- Can you please inform me which part of the code represents the front end module?
- I used used data augmentation , but for some reason I obtained bad results. Why did that happen?


Thanks in advance

**Comment by yoshiinet** [comment]
I re-experimented with the current code(pptunetf-final.py). As a result, I have confirmed that the results of the paper were certainly not obtained as you pointed out.
I will find out where the cause is and also look for answers to the remaining questions.
I apologize for any inconvenience

**_Below, I will add the results of the subsequent survey._**

### [experimental results]
In "./run/pptunetf/pptunetf-final.py",
hyper_params_v5 corresponds to Table 4 (A),
hyper_params_v4 corresponds to Table 4 (B) (data_size = -1), and
hyper_params_v4a corresponds to Table 4 (C) (data_size = -2).

As a result of the reproduction experiment, the result is different from Table 4 in each case.
It seems that the code has changed when I upload it to Github, but unfortunately I can't find the history, so it's unclear where it changed.
As an alternative, I have created a revised version of the [**paper**](https://github.com/yoshiinet/dcase2021_task2_ar_frame_seq_model/files/8769497/Abe_RLB_task2.technical_report_table4_revised.pdf)   (Revised May 25 2020), including Table.4, with the current source code.

### [answers to the remaining questions]

- The front-end module (Paper Table.2) corresponds to the following code near line 395 of "./model/pptunetf.py".
```
        self.transformer = TransformerEncoderBuilder.from_kwargs(
            n_layers=n_enc_l,
            n_heads=nhead,
            query_dimensions=d_model//nhead,
            value_dimensions=d_model//nhead,
            feed_forward_dimensions=d_ff,
            attention_type = attn_type,
            activation="relu", # activation: Choose which activation to use
                               # for the feed forward part of the layer from
                               # the set {'relu', 'gelu'} (default: relu)
            dropout=dropout_factor,
            attention_dropout=dropout_factor,
            ).get()
```
- Data augmentation has not been fully verified, so I can't say anything about it.

**Comment by ahmedshamel1** [comment]
Prof. Yoshiharu

I am very thankful for all your help and sorry for wasting your time. If you can just allow me to ask one more question.
- I know aug_wcut is used for cutting the waveform, but what does the number represents (aug_wcut=1024) ? Is it the number of samples?
- how can cutting the wave form helps in improving the results ?
- when adding Gaussian random noise shouldn't the signal-to-noise ratio be greater than or equal 0 dB  to make sure that signal level is greater than the noise level? As I can not find it in the code.
